apiVersion: v1
kind: Service
metadata:
  labels:
    app: democicd
  name: democicd
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: democicd
  type: NodePort
